--
-- Built with,
--
--        ,gggg,
--       d8" "8I                         ,dPYb,
--       88  ,dP                         IP'`Yb
--    8888888P"                          I8  8I
--       88                              I8  8'
--       88        gg      gg    ,g,     I8 dPgg,
--  ,aa,_88        I8      8I   ,8'8,    I8dP" "8I
-- dP" "88P        I8,    ,8I  ,8'  Yb   I8P    I8
-- Yb,_,d88b,,_   ,d8b,  ,d8b,,8'_   8) ,d8     I8,
--  "Y8P"  "Y888888P'"Y88P"`Y8P' "YY8P8P88P     `Y8
--

local lush = require('lush')
local hsl = lush.hsl

-- Naming convention for palette entries follows [color]_[lightness]
-- where color is based off of hue and saturation.
local palette = {
  taupe_10 = hsl(20, 12, 10),
  taupe_15 = hsl(20, 12, 15),
  taupe_35 = hsl(20, 12, 35),
  taupe_50 = hsl(20, 12, 50),
  taupe_70 = hsl(20, 12, 70),
  taupe_80 = hsl(20, 12, 80),
  taupe_90 = hsl(20, 12, 90),
  grey_70 = hsl(20, 6, 70),
  grey_80 = hsl(20, 6, 80),
  white = hsl(0, 0, 100),
  yellow = hsl(45, 65, 50),
  purple = hsl(270, 50, 70),
  pink = hsl(300, 50, 70),
  green = hsl(77, 74, 39),
  blue = hsl(191, 74, 45),
  red = hsl(0, 60, 40),
  orange = hsl(25, 65, 50)
}

-- highlights that something is unset
local noop = palette.pink

-- noop values must be set depending on vim.o.background
-- default values might be overridden
local tokens = {
  background = noop,
  surface_1 = noop,
  surface_2 = noop,
  surface_3 = noop,
  surface_4 = noop,
  text_muted = noop,
  text_default = noop,
  text_normal = noop,
  text_highlight = palette.white,
  string_literal = palette.green,
  number_literal = palette.purple,
  keyword_literal = palette.purple,
  special = noop,
  special_muted = noop,
  error = palette.red,
  warn = palette.orange,
  label = palette.orange,
  hint = palette.blue,
}

if vim.o.background == "light" then
  local background = palette.taupe_90
  tokens.background = background

  local surface_base = background.darken(5)
  tokens.surface_1 = surface_base
  tokens.surface_2 = surface_base.darken(20)
  tokens.surface_3 = surface_base.darken(25)
  tokens.surface_4 = surface_base.darken(50)

  local text_base = background.darken(45)
  tokens.text_default = text_base
  tokens.text_normal = text_base.darken(25)
  tokens.text_muted = text_base.lighten(25)

  tokens.string_literal = palette.green.darken(15)
  tokens.number_literal = palette.pink.darken(25)
  tokens.keyword_literal = palette.pink.darken(25)
  tokens.label = palette.orange

  tokens.special = palette.blue
  tokens.special_muted = palette.blue.lighten(20)
else
  local background = palette.taupe_10
  tokens.background = background

  local surface_base = background.lighten(5)
  tokens.surface_1 = surface_base
  tokens.surface_2 = surface_base.lighten(20)
  tokens.surface_3 = surface_base.lighten(35)
  tokens.surface_4 = surface_base.lighten(70)

  tokens.text_default = palette.grey_70
  tokens.text_normal = palette.grey_80
  tokens.text_muted = palette.grey_70.darken(30)

  tokens.special = palette.yellow
  tokens.special_muted = palette.yellow.darken(20)
end

-- set ghostty theme based on neovim theme
-- requires manual ghostty theme reloading, e.g. cmd+shift+r
local function write_ghostty_theme()
  local filepath = os.getenv("HOME") .. "/.config/ghostty/themes/auto_neovim"
  local file, err = io.open(filepath, "w")

  local ghostty_theme = {
    cursor_color = noop,
    cursor_text = noop,
    background = noop,
    foreground = noop,
    selection_background = noop,
    selection_foreground = noop
  }

  ghostty_theme.cursor_color = tokens.surface_4
  ghostty_theme.cursor_text = tokens.background
  ghostty_theme.background = tokens.background
  ghostty_theme.foreground = tokens.text_default

  if file then
    file:write("# THIS FILE IS AUTOMATICALLY GENERATED BY NEOVIM.")
    file:write("\ncursor-color=" .. ghostty_theme.cursor_color.hex)
    file:write("\ncursor-text=" .. ghostty_theme.cursor_text.hex)
    file:write("\nbackground=" .. ghostty_theme.background.hex)
    file:write("\nforeground=" .. ghostty_theme.foreground.hex)
    file:write("\nselection-background=" .. ghostty_theme.selection_background.hex)
    file:write("\nselection-foreground=" .. ghostty_theme.selection_foreground.hex)
    file:close()
  else
    error("Failed to open file at " .. filepath .. ": " .. err)
  end
end

local function write_tmux_theme()
  local filepath = os.getenv("HOME") .. "/.config/tmux/themes/auto_neovim"
  local file, err = io.open(filepath, "w")

  local tmux_theme = {
    status_style_fg = tokens.surface_2,
    status_style_bg = tokens.surface_1,
    message_style_fg = tokens.text_highlight,
    message_style_bg = tokens.special,
    window_status_current_style_fg = palette.blue,
    window_status_current_style_bg = tokens.surface_1,
    window_style_fg = tokens.text_normal,
    window_style_bg = tokens.surface_1,
    pane_border_style_fg = tokens.surface_1,
    pane_active_border_style_fg = tokens.surface_1,
  }

  if file then
    file:write("# THIS FILE IS AUTOMATICALLY GENERATED BY NEOVIM.")
    file:write("\nset -g status-style 'fg=" .. tmux_theme.status_style_fg.hex .. " bg=" .. tmux_theme.status_style_bg.hex .. "'")
    file:write("\nset -g message-style 'fg=" .. tmux_theme.message_style_fg.hex .. " bg=" .. tmux_theme.message_style_bg.hex .. "'")
    file:write("\nset -g window-style 'fg=" .. tmux_theme.window_style_fg.hex .. " bg=" .. tmux_theme.window_style_bg.hex .. "'")
    file:write("\nset -g window-status-current-style 'fg=" .. tmux_theme.window_status_current_style_fg.hex .. " bg=" .. tmux_theme.window_status_current_style_bg.hex .. " bold'")
    file:write("\nset -g pane-border-style 'fg=" .. tmux_theme.pane_border_style_fg.hex .. "'")
    file:write("\nset -g pane-active-border-style 'fg=" .. tmux_theme.pane_active_border_style_fg.hex .. "'")
    file:close()
  else
    error("Failed to open file at " .. filepath .. ": " .. err)
  end
end

write_ghostty_theme()
write_tmux_theme()

local theme = lush(function(injected_functions)
  local sym = injected_functions.sym
  return {
    CursorLine     { bg=tokens.surface_1 }, -- Screen-line at the cursor, when 'cursorline' is set. Low-priority if foreground (ctermfg OR guifg) is not set.
    ColorColumn    { CursorLine }, -- Columns set with 'colorcolumn'
    CursorColumn   { CursorLine }, -- Screen-column at the cursor, when 'cursorcolumn' is set.
    -- Conceal        { }, -- Placeholder characters substituted for concealed text (see 'conceallevel')
    Search         { fg=tokens.text_highlight, bg=tokens.special_muted }, -- Last search pattern highlighting (see 'hlsearch'). Also used for similar items that need to stand out.
    CurSearch      { Search }, -- Highlighting a search pattern under the cursor (see 'hlsearch')
    IncSearch      { Search }, -- 'incsearch' highlighting; also used for the text replaced with ":s///c"
    Substitute     { Search }, -- |:substitute| replacement text highlighting

    Cursor         { fg=tokens.background, bg=palette.taupe_10 }, -- Character under the cursor
    -- lCursor        { }, -- Character under the cursor when |language-mapping| is used (see 'guicursor')
    -- CursorIM       { }, -- Like Cursor, but used when in IME mode |CursorIM|
    -- Directory      { }, -- Directory names (and other special names in listings)
    -- DiffAdd        { }, -- Diff mode: Added line |diff.txt|
    -- DiffChange     { }, -- Diff mode: Changed line |diff.txt|
    -- DiffDelete     { }, -- Diff mode: Deleted line |diff.txt|
    -- DiffText       { }, -- Diff mode: Changed text within a changed line |diff.txt|
    -- EndOfBuffer    { }, -- Filler lines (~) after the end of the buffer. By default, this is highlighted like |hl-NonText|.
    -- TermCursor     { }, -- Cursor in a focused terminal
    -- TermCursorNC   { }, -- Cursor in an unfocused terminal
    -- ErrorMsg       { }, -- Error messages on the command line

    LineNr         { fg=tokens.surface_2 }, -- Line number for ":number" and ":#" commands, and when 'number' or 'relativenumber' option is set.
    LineNrAbove    { LineNr }, -- Line number for when the 'relativenumber' option is set, above the cursor line
    LineNrBelow    { LineNr }, -- Line number for when the 'relativenumber' option is set, below the cursor line
    CursorLineNr   { fg=tokens.special, gui="bold" }, -- Like LineNr when 'cursorline' or 'relativenumber' is set for the cursor line.

    VertSplit      { fg=tokens.surface_2 }, -- Column separating vertically split windows
    Winseparator   { VertSplit }, -- Separator between window splits. Inherts from |hl-VertSplit| by default, which it will replace eventually.

    -- CursorLineFold { }, -- Like FoldColumn when 'cursorline' is set for the cursor line
    -- CursorLineSign { }, -- Like SignColumn when 'cursorline' is set for the cursor line
    Folded         { fg=tokens.special, bg=tokens.surface_1, gui="NONE" }, -- Line used for closed folds
    -- FoldColumn     { }, -- 'foldcolumn'
    SignColumn     { bg=tokens.background }, -- Column where |signs| are displayed
    MatchParen     { fg=tokens.text_default, bg=tokens.surface_2 }, -- Character under the cursor or just before it, if it is a paierror bracket, and its match. |pi_paren.txt|
    ModeMsg        { fg=tokens.special, gui='bold' }, -- 'showmode' message (e.g., "-- INSERT -- ")
    -- MsgArea        { }, -- Area for messages and cmdline
    -- MsgSeparator   { }, -- Separator for scrolled messages, `msgsep` flag of 'display'
    -- MoreMsg        { }, -- |more-prompt|
    -- NonText        { }, -- '@' at the end of the window, characters from 'showbreak' and other characters that do not really exist in the text (e.g., ">" displayed when a double-wide character doesn't fit at the end of the line). See also |hl-EndOfBuffer|.

    Normal         { fg=tokens.text_default, bg=tokens.background }, -- Normal text
    -- NormalNC       { }, -- normal text in non-current windows

    NormalFloat    { Normal, bg=tokens.surface_1 }, -- Normal text in floating windows.
    -- FloatBorder    { }, -- Border of floating windows.
    -- FloatTitle     { }, -- Title of floating windows.

    Pmenu          { fg=tokens.text_default, bg=tokens.surface_1 }, -- Popup menu: Normal item.
    PmenuSel       { fg=tokens.text_highlight, bg=tokens.surface_2 }, -- Popup menu: Selected item.
    -- PmenuKind      { }, -- Popup menu: Normal item "kind"
    -- PmenuKindSel   { }, -- Popup menu: Selected item "kind"
    -- PmenuExtra     { }, -- Popup menu: Normal item "extra text"
    -- PmenuExtraSel  { }, -- Popup menu: Selected item "extra text"
    -- PmenuSbar      { }, -- Popup menu: Scrollbar.
    -- PmenuThumb     { }, -- Popup menu: Thumb of the scrollbar.
    -- Question       { }, -- |hit-enter| prompt and yes/no questions
    -- QuickFixLine   { }, -- Current |quickfix| item in the quickfix window. Combined with |hl-CursorLine| when the cursor is there.
    -- SpecialKey     { }, -- Unprintable characters: text displayed differently from what it really is. But not 'listchars' whitespace. |hl-Whitespace|
    -- SpellBad       { }, -- Word that is not recognized by the spellchecker. |spell| Combined with the highlighting used otherwise.
    -- SpellCap       { }, -- Word that should start with a capital. |spell| Combined with the highlighting used otherwise.
    -- SpellLocal     { }, -- Word that is recognized by the spellchecker as one that is used in another region. |spell| Combined with the highlighting used otherwise.
    -- SpellRare      { }, -- Word that is recognized by the spellchecker as one that is hardly ever used. |spell| Combined with the highlighting used otherwise.
    StatusLine     { fg=tokens.surface_3, bg=tokens.surface_1 }, -- Status line of current window
    StatusLineNC   { fg=tokens.surface_2, bg=tokens.surface_1 }, -- Status lines of not-current windows. Note: If this is equal to "StatusLine" Vim will use "^^^" in the status line of the current window.
    -- TabLine        { }, -- Tab pages line, not active tab page label
    -- TabLineFill    { }, -- Tab pages line, where there are no labels
    -- TabLineSel     { }, -- Tab pages line, active tab page label
    -- Title          { }, -- Titles for output from ":set all", ":autocmd" etc.
    Visual         { fg=tokens.special, bg=tokens.surface_1 }, -- Visual mode selection
    VisualNOS      { fg=tokens.special, bg=tokens.surface_1 }, -- Visual mode selection when vim is "Not Owning the Selection".
    -- WarningMsg     { }, -- Warning messagetat
    -- Whitespace     { }, -- "nbsp", "space", "tab" and "trail" in 'listchars'
    -- WildMenu       { }, -- Current match in 'wildmenu' completion
    -- WinBar         { }, -- Window bar of current window
    -- WinBarNC       { }, -- Window bar of not-current windows

    -- Common vim syntax groups used for all kinds of code and markup.
    -- Commented-out groups should chain up to their prefererror (*) group
    -- by default.
    --
    -- See :h group-name
    --
    -- Uncomment and edit if you want more specific syntax highlighting.

    Comment        { fg=tokens.text_muted }, -- Any comment

    String         { fg=tokens.string_literal }, --   A string constant: "this is a string"
    Character      { String }, --   A character constant: 'c', '\n'
    Constant       { String }, -- (*) Any constant
    Number         { fg=tokens.number_literal }, --   A number constant: 234, 0xff
    Boolean        { Number, gui='bold' }, --   A boolean constant: TRUE, false
    Float          { Number }, --   A floating point constant: 2.3e10

    Identifier     { fg=tokens.text_default }, -- (*) Any variable name
    Keyword        { Identifier, gui="bold" }, --   any other keyword
    Statement      { Keyword }, -- (*) Any statement
    -- Conditional    { }, --   if, then, else, endif, switch, etc.
    -- Repeat         { }, --   for, do, while, etc.
    -- Label          { }, --   case, default, etc.
    Operator       { fg=tokens.text_default, gui='bold' }, --   "sizeof", "+", "*", etc.
    -- Exception      { }, --   try, catch, throw

    -- PreProc        { }, -- (*) Generic Preprocessor
    -- Include        { }, --   Preprocessor #include
    -- Define         { }, --   Preprocessor #define
    -- Macro          { }, --   Same as Define
    -- PreCondit      { }, --   Preprocessor #if, #else, #endif, etc.

    -- Type           { }, -- (*) int, long, char, etc.
    -- StorageClass   { }, --   static, register, volatile, etc.
    -- Structure      { }, --   struct, union, enum, etc.
    -- Typedef        { }, --   A typedef

    Special        { fg=tokens.text_default }, -- (*) Any special symbol
    -- SpecialChar    { }, --   Special character in a constant
    -- Tag            { }, --   You can use CTRL-] on this
    Delimiter      { fg=tokens.text_default }, --   Character that needs attention
    -- SpecialComment { }, --   Special things inside a comment (e.g. '\n')
    -- Debug          { }, --   Debugging statements

    -- Underlined     { gui = "underline" }, -- Text that stands out, HTML links
    -- Ignore         { }, -- Left blank, hidden |hl-Ignore| (NOTE: May be invisible here in template)
    -- Error          { }, -- Any erroneous construct
    Todo           { Comment, gui='bold' }, -- Anything that needs extra attention; mostly the keywords TODO FIXME and XXX

    -- These groups are for the native LSP client and diagnostic system. Some
    -- other LSP clients may use these groups, or use their own. Consult your
    -- LSP client's documentation.

    -- See :h lsp-highlight, some groups may not be listed, submit a PR fix to lush-template!
    --
    -- LspReferenceText            { } , -- Used for highlighting "text" references
    -- LspReferenceRead            { } , -- Used for highlighting "read" references
    -- LspReferenceWrite           { } , -- Used for highlighting "write" references
    -- LspCodeLens                 { } , -- Used to color the virtual text of the codelens. See |nvim_buf_set_extmark()|.
    -- LspCodeLensSeparator        { } , -- Used to color the seperator between two or more code lens.
    -- LspSignatureActiveParameter { } , -- Used to highlight the active parameter in the signature help. See |vim.lsp.handlers.signature_help()|.

    -- See :h diagnostic-highlights, some groups may not be listed, submit a PR fix to lush-template!
    --
    DiagnosticError            { fg=tokens.error, gui='bold' } , -- Used as the base highlight group. Other Diagnostic highlights link to this by default (except Underline)
    DiagnosticWarn             { fg=tokens.warn, gui='bold' } , -- Used as the base highlight group. Other Diagnostic highlights link to this by default (except Underline)
    DiagnosticInfo             { fg=tokens.special, gui='bold' } , -- Used as the base highlight group. Other Diagnostic highlights link to this by default (except Underline)
    DiagnosticHint             { fg=tokens.hint, gui='bold' } , -- Used as the base highlight group. Other Diagnostic highlights link to this by default (except Underline)
    -- DiagnosticOk               { } , -- Used as the base highlight group. Other Diagnostic highlights link to this by default (except Underline)
    -- DiagnosticVirtualTextError { } , -- Used for "Error" diagnostic virtual text.
    -- DiagnosticVirtualTextWarn  { } , -- Used for "Warn" diagnostic virtual text.
    -- DiagnosticVirtualTextInfo  { } , -- Used for "Info" diagnostic virtual text.
    -- DiagnosticVirtualTextHint  { } , -- Used for "Hint" diagnostic virtual text.
    -- DiagnosticVirtualTextOk    { } , -- Used for "Ok" diagnostic virtual text.
    -- DiagnosticUnderlineError   { } , -- Used to underline "Error" diagnostics.
    -- DiagnosticUnderlineWarn    { } , -- Used to underline "Warn" diagnostics.
    -- DiagnosticUnderlineInfo    { } , -- Used to underline "Info" diagnostics.
    -- DiagnosticUnderlineHint    { } , -- Used to underline "Hint" diagnostics.
    -- DiagnosticUnderlineOk      { } , -- Used to underline "Ok" diagnostics.
    -- DiagnosticFloatingError    { } , -- Used to color "Error" diagnostic messages in diagnostics float. See |vim.diagnostic.open_float()|
    -- DiagnosticFloatingWarn     { } , -- Used to color "Warn" diagnostic messages in diagnostics float.
    -- DiagnosticFloatingInfo     { } , -- Used to color "Info" diagnostic messages in diagnostics float.
    -- DiagnosticFloatingHint     { } , -- Used to color "Hint" diagnostic messages in diagnostics float.
    -- DiagnosticFloatingOk       { } , -- Used to color "Ok" diagnostic messages in diagnostics float.
    -- DiagnosticSignError        { } , -- Used for "Error" signs in sign column.
    -- DiagnosticSignWarn         { } , -- Used for "Warn" signs in sign column.
    -- DiagnosticSignInfo         { } , -- Used for "Info" signs in sign column.
    -- DiagnosticSignHint         { } , -- Used for "Hint" signs in sign column.
    -- DiagnosticSignOk           { } , -- Used for "Ok" signs in sign column.

    TelescopeResultsNormal { fg=tokens.surface_3 },
    TelescopeSelectionCaret { TelescopeResultsNormal, bg=tokens.surface_1 },
    TelescopeMatching { fg=tokens.special, gui='bold' },
    TelescopeSelection { fg=tokens.special_muted, bg=tokens.surface_1 }, 

    -- Tree-Sitter syntax groups.
    --
    -- See :h treesitter-highlight-groups, some groups may not be listed,
    -- submit a PR fix to lush-template!
    --
    -- Tree-Sitter groups are defined with an "@" symbol, which must be
    -- specially handled to be valid lua code, we do this via the special
    -- sym function. The following are all valid ways to call the sym function,
    -- for more details see https://www.lua.org/pil/5.html
    --
    -- sym("@text.literal")
    -- sym('@text.literal')
    -- sym"@text.literal"
    -- sym'@text.literal'
    --
    -- For more information see https://github.com/rktjmp/lush.nvim/issues/109

    -- sym"@text.literal"      { }, -- Comment
    -- sym"@text.reference"    { }, -- Identifier
    -- sym"@text.title"        { }, -- Title
    -- sym"@text.uri"          { }, -- Underlined
    -- sym"@text.underline"    { }, -- Underlined
    -- sym"@text.todo"         { }, -- Todo
    -- sym"@comment"           { }, -- Comment
    sym"@punctuation"       { Delimiter }, -- Delimiter
    sym"@constant"          { fg=tokens.text_default }, -- Constant
    -- sym"@constant.builtin"  { }, -- Special
    -- sym"@constant.macro"    { }, -- Define
    -- sym"@define"            { }, -- Define
    -- sym"@macro"             { }, -- Macro
    -- sym"@string"            { }, -- String
    -- sym"@string.escape"     { }, -- SpecialChar
    -- sym"@string.special"    { }, -- SpecialChar
    -- sym"@character"         { }, -- Character
    -- sym"@character.special" { }, -- SpecialChar
    -- sym"@number"            { }, -- Number
    -- sym"@boolean"           { }, -- Boolean
    -- sym"@float"             { }, -- Float
    -- sym"@function"          { }, -- Function
    -- sym"@function.builtin"  { }, -- Special
    -- sym"@function.macro"    { }, -- Macro
    -- sym"@parameter"         { }, -- Identifier
    -- sym"@method"            { }, -- Function
    -- sym"@field"             { }, -- Identifier
    sym"@property"          { fg=tokens.text_default }, -- Identifier
    -- sym"@constructor"       { }, -- Special
    -- sym"@conditional"       { }, -- Conditional
    -- sym"@repeat"            { }, -- Repeat
    -- sym"@label"             { }, -- Label
    -- sym"@operator"          { }, -- Operator
    -- sym"@keyword"           { }, -- Keyword
    -- sym"@exception"         { }, -- Exception
    sym"@variable"          { fg=tokens.text_default }, -- Identifier
    -- sym"@type"              { }, -- Type
    -- sym"@type.definition"   { }, -- Typedef
    -- sym"@storageclass"      { }, -- StorageClass
    -- sym"@structure"         { }, -- Structure
    -- sym"@namespace"         { }, -- Identifier
    -- sym"@include"           { }, -- Include
    -- sym"@preproc"           { }, -- PreProc
    -- sym"@debug"             { }, -- Debug
    -- sym"@tag"               { }, -- Tag
    sym"@lsp.type.keywordLiteral.zig" { fg=tokens.keyword_literal }, -- e.g. null
    sym"@lsp.type.label.zig"          { fg=tokens.label, gui='bold' }, -- e.g. blk:/:blk
    -- sym"@keyword.exception.zig"       { fg=palette.label, gui='bold' }, -- e.g. try
    sym"@lsp.type.type.zig"           { fg=tokens.text_default, gui='bold' },
    sym"@lsp.type.namespace.zig"      { fg=tokens.text_default }, -- references to namespaces, e.g. std
    sym"@lsp.type.builtin.zig"        { fg=tokens.special, gui='bold' }, -- e.g. @import

    sym"@string" { String },
    sym"@string.escape" { String },

    sym"@function" { fg=tokens.special, gui='bold' },
    Function                    { fg=tokens.text_default, gui='bold' },
    sym"@function.call"         { Function }, -- struct method calls
    sym"@lsp.type.function.zig" { Function }, -- function/enum method references/calls
    sym"@lsp.type.method.zig"   { Function }, -- struct method calls
    sym"@lsp.type.method.lua" { Function },

    LspFunctionDecl { fg=tokens.special },
    sym"@lsp.typemod.method.declaration.zig" { LspFunctionDecl }, -- function defined on struct
    sym"@lsp.typemod.function.declaration.zig" { LspFunctionDecl }, -- function defined on enum (?) and elsewhere


    LspTypeDecl { fg=tokens.special, gui='bold' },
    LspTypeRef { fg=tokens.text_normal, gui='bold' },
    sym"@lsp.typemod.enum.declaration.zig" { LspTypeDecl },
    sym"@lsp.type.enum.zig" { LspTypeRef },
    sym"@lsp.typemod.type.declaration.zig" { LspTypeDecl },
    sym"@lsp.type.union.zig" { LspTypeRef },
    sym"@lsp.typemod.struct.declaration.zig" { LspTypeDecl }, -- struct declaration
    sym"@lsp.type.struct.zig" { LspTypeRef}, -- struct type reference


    zigDummyVariable { fg=tokens.text_default  }, -- the underscore

    sym"@markup.link.vimdoc" { fg=tokens.text_default, gui='bold' },
    sym"@label.vimdoc" { fg=tokens.special, gui='bold' }
}
end)

-- Return our parsed theme for extension or use elsewhere.
return theme
